### ISSUE TITLE
User code should not be a library

### ISSUE THREAD

**Issue by AustinShalit** [WPIRoboticsEngineering/RBE2001_template#2]
It does not make sense for user robot code to be a library.  Libraries, by definition, should be portable and have the possibility of being used by multiple programs.  The code we will be writing does not meet this criteria.  Instead of writing a library, we should be writing user code (code that uses libraries).

This is backwards and not how things are done in real projects.

**Comment by madhephaestus** [comment]
a pedagogical objective is the ability to set up a correct arduino library.
