### ISSUE TITLE
Add MyRobot::Setup

### ISSUE THREAD

**Issue by AustinShalit** [WPIRoboticsEngineering/RBE2001_template#6]
For initialization code after the other libs are setup.

**Comment by madhephaestus** [comment]
thats what the constructor is for.

**Comment by AustinShalit** [comment]
No, what if I need initalization code after the other libraries are initialized?

**Comment by AustinShalit** [comment]
Reopening this because if interrupts are setup and firing while wifi is trying to initialize, the robot controller will crash.  Do we have permission to add this ourselves?

**Comment by AustinShalit** [comment]
I can't reopen this.
